pipeline {
    agent any

    stages {
        stage('Execute Unit Tests') {
            parallel {
                stage('Unit Tests - Backend') {
                    agent {
                        docker {
                            image 'golang:1.26.1-alpine'
                            reuseNode true
                        }
                    }
                    steps {
                        dir('bugtracker-backend') {
                            sh '''
                            mkdir -p /tmp/go-build
                            export GOCACHE=/tmp/go-build
                            go test -v ./...

                            # Generate coverage report
                            go test -coverprofile=coverage.out -covermode=atomic ./...
                            go tool cover -html=coverage.out -o coverage.html

                            mkdir -p reports
                            mv coverage.html reports/
                            '''
                        }
                    }
                    post {
                        always {
                            publishHTML target: [
                                reportDir: 'bugtracker-backend/reports',
                                reportFiles: 'coverage.html',
                                reportName: 'Backend Coverage Report'
                            ]
                        }
                    }
                }

                stage('Unit Tests - Frontend') {
                    agent {
                        docker {
                            image 'node:25.8.1-alpine'
                            reuseNode true
                        }
                    }
                    steps {
                        dir('bugtracker-frontend') {
                            sh '''
                            npm ci
                            npm test
                            mkdir -p reports
                            mv coverage reports/
                            '''
                        }
                    }
                    post {
                        always {
                            junit 'bugtracker-frontend/test-results.xml'
                            publishHTML target: [
                                reportDir: 'bugtracker-frontend/reports/coverage',
                                reportFiles: 'index.html',
                                reportName: 'Frontend Coverage Report'
                            ]
                        }
                    }
                }
            }
        }
    }
    post {
        always {
            cleanWs()
        }
    }
}