pipeline {
    agent {
        docker {
            image 'snakee/golang-junit:1.22'
            reuseNode true
        }
    }

    stages {
        stage('Unit Tests - Backend') {
            steps {
                dir('bugtracker-backend') {
                    sh 'go test -v ./...'
                }
            }
        }
    }
}